name: example-environment
channels:
  - conda-forge
dependencies:
  -- python>=3.5
  - numpy
  - psutil
  - toolz
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - scikit-image
  - scikit-learn
  - matplotlib>=3.0.1
  - opencv
