name: example-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.6
  - psutil
  - toolz
  - dill
  - partd
  - bokeh
  - dask
  - scikit-image
  - scikit-learn
  - matplotlib
  - numpy
  - opencv
  - pandas
