name: example-environment
channels:
  - conda-forge
dependencies:
  -- python>=3.7
  - numpy
  - psutil
  - toolz
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - scikit-learn>=0.19
  - matplotlib>=2.0
  - scikit-image
  - opencv
