name: example-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - psutil
  - toolz
  - dill
  - partd
  - bokeh
  - dask
  - scikit-image
  - scikit-learn==0.18.1
  - matplotlib
  - python==3.6
  - numpy==1.12
  - scipy==0.19.1
  - scikit-learn==0.18.1
  - opencv==3.1
  - pandas==0.22
